- name: Create Application Secrets
  community.okd.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: app-secrets
        namespace: microservice-demo
      type: Opaque
      data:
        DB_PASSWORD: base64_encoded_value

- name: Create ConfigMap
  community.okd.k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: app-config
        namespace: microservice-demo
      data:
        app.properties: |
          ENVIRONMENT=dev
          LOG_LEVEL=INFO
